version: '3.9'

services:
  app:
    build: 
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"  #maps the port on local to port in container
    volumes:
      - ./app:/app #maps app director to the container
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"